name    'ajcrowe-confd'
version '0.2.1'
source 'https://github.com/ajcrowe/puppet-confd.git'
author 'Alex Crowe'
license 'MIT'
summary 'confd class and functions'
description 'confd class and functions'
project_page 'https://github.com/ajcrowe/puppet-confd'

dependency 'puppetlabs/concat', '>= 1.0.0 <2.0.0'
